### PR TITLE
use autotools to build dsf2flac

### PR DESCRIPTION
**Pull request by mishan**
Had to add a couple of m4 files because I couldn't find the boost timer one on my system and the installed libFLAC++ one was broken and needed an ugly hack

Also had to fix some build errors as far as header include syntax (local vs system) and rename main.c to main.cpp

Removed the dsf2flac.\* IDE build files as they're environment/IDE specific

### CODE REVIEW

**Comment by mishan** [comment]
This addresses issue #1

**Comment by hank** [comment]
Great work.  Got it working in Linux perfectly, but I'm still struggling in Cygwin.  Hopefully I'll have it working soon there.  Thanks!

**Comment by mishan** [comment]
@hank You may want to merge some more changes from this PR. One of the commits removes `libFLAC++.m4` entirely as it's not needed -- I should have used `AC_LANG(C++)` in the first place. I think if someone has a library installed they should generally have the m4 macro script that we shouldn't need to ship it with the source, which is why I wittled it down to the missing `ax_boost_timer.m4` in the end

**Comment by mishan** [comment]
If you want, I can rebase this and omit the rest of the changes from README.txt, or you can pick apart the other changes at your leisure. Let me know.

**Comment by hank** [comment]
A bunch of the aclocal m4s are missing at least in Cygwin, and I'd like to support Cygwin compilation if possible.  I'm dorking around with it a bit more tonight and I'll take a look at the rest of the changes.

**Comment by hank** [comment]
Just tested - builds in Linux and ALMOST builds in Cygwin - something is wrong with libtool in my Cygwin env, so linking fails, but it would work if that wasn't busted.

**Comment by mishan** [comment]
Cool! re: libtool -- I originally was using libtool with the autotools stuff I created (and I'm rather rusty on autotools, it's been almost a decade since I have mucked with autotools) but then I realized it wasn't necessary.

I had gotten rid of any libtool refs in configure.ac (just needed AC_PROG_RANLIB) and src/libdstdec/Makefile.am and such. As far as I understand (please correct me if I'm wrong), you only need libtools if you intend to make the library built in src/libdstdec as something that can be installed on the system (for other software to potentially link against) and to be used as a runtime dependency.

If you don't need to have it installed as a library (the binary builds just fine and includes libdstdec statically without libtool), then you can probably drop libtool out of the equation and simplify things.

**Comment by hank** [comment]
The only reason I went to libtool was because I kept failing aclocal because of a missing AC_MSG_ERROR macro.  I have no idea why this was "missing," but after reading about various people having the same problem and adding libtool, it did fix the issue.  I may try switching back, but it seems to work OK for now in Linux at least.  Also, I added some checks for taglib and such, so it validates all those now.  Perhaps I'll go back to the old way with RANLIB and see if something else I changed happened to fix that AC_MSG_ERROR issue I was having.  Autotools is mysterious and hard to use, but it does work nearly everywhere.  If this weren't in good shape already I'd consider using CMake or scons instead because it would be much easier to deal with, but thanks for putting this together into something reasonable to build!

**Pull request closed without merging**
